version: 2.1

setup: true

orbs:
  flutter: circleci/flutter@2.0.2

parameters:
  cd_run:
    type: boolean
    default: false

executor:
  flutter_executor:
    macos:
      xcode: 14.2.0

jobs:
#    executor: flutter_executor
#    steps:
##      - checkout
##      - flutter/install_sdk:
##          version: << pipeline.parameters.flutter-version >>
##      - run: flutter pub global activate melos
##      - run: flutter pub global run melos bootstrap
##      - run: flutter pub global run melos run daily_memo_pub_get
  test:
    run: echo "test daily memo"

workflows:
  ci:
    when:
      equal: [ true, << pipeline.parameters.cd_run >> ]
    jobs:
      - test