version: 2.1

setup: true

orbs:
  flutter: circleci/flutter@2.0.2

parameters:
  cd_run:
    type: boolean
    default: false

executor:
  flutter_executor:
    macos:
      xcode: 14.2.0

jobs:
  test:
    macos:
      xcode: 14.2.0
    steps:
      - run:
          command: echo "test daily memo deploy1"

  test2:
    macos:
      xcode: 14.2.0
    steps:
      - run:
          command: echo "test daily memo deploy2"

workflows:
  ci:
    when:
      equal: [ true, << pipeline.parameters.cd_run >> ]
    jobs:
      - test