version: 2.1

parameter:
  flutter-version:
    type: string
    default: "3.3.10"

orbs:
  flutter: circleci/flutter@2.0.2

executor:
  flutter_executor:
    macos:
      xcode: 14.2.0

jobs:
  test:
#    executor: flutter_executor
    steps:
#      - checkout
#      - flutter/install_sdk:
#          version: << pipeline.parameters.flutter-version >>
#      - run: flutter pub global activate melos
#      - run: flutter pub global run melos bootstrap
#      - run: flutter pub global run melos run daily_memo_pub_get
      - run: echo "test"

workflows:
  ci:
    - test
