name: spiralDev

packages:
  - "apps/*"
  - "packages/**"

ignore:
  - "apps/exchange_rate_calculator"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  daily_memo_pub_get:
    run: flutter pub global run melos exec --scope="apps.daily_memo" -- flutter clean && flutter pub global run melos exec --scope="apps.daily_memo" -- flutter pub get
    description: daily memo pub get

