version: 2.1

parameters:
  cd_run:
    type: boolean
    default: false

jobs:
  test:
    macos:
      xcode: 14.2.0
    steps:
      - run:
          command: echo "test exchange cal deploy1"

  test2:
    macos:
      xcode: 14.2.0
    steps:
      - run:
          command: echo "test exchange cal deploy2"

workflows:
  ci:
    when:
      equal: [ true, << pipeline.parameters.cd_run >> ]
    jobs:
      - test
