version: 2.1

setup: true

orbs:
  flutter: circleci/flutter@2.0.2

parameters:
  daily_memo_ci_run:
    type: boolean
    default: false
  exchange_calculator_ci_run:
    type: boolean
    default: false

jobs:
  #  ci:
  #    macos:
  #      xcode: 14.2.0
  #    steps:
  #      - checkout
  #      - flutter/install_sdk:
  #          version: 3.3.10
  #      - run: flutter pub global activate melos 2.9.0
  #      - run: flutter pub global run melos bootstrap
  #      - run: flutter pub global run melos run exchange_rate_calculator_pub_get
    - test:
      run: echo "test daily memo"

    - test2:
      run: echo "test exchange cal"


workflows:
  ci:
    when:
      equal: [ true, << pipeline.parameters.daily_memo_ci_run >> ]
    jobs:
      - test
  ci2:
    when:
      equal: [ true, << pipeline.parameters.exchange_calculator_ci_run >> ]
    jobs:
      - test2
