version: '2.1'

orbs:
  flutter: circleci/flutter@2.0.2

parameters:
  daily_memo_ci_run:
    type: boolean
    default: false
  exchange_calculator_ci_run:
    type: boolean
    default: false

jobs:
  #  ci:
  #    macos:
  #      xcode: 14.2.0
  #    steps:
  #      - checkout
  #      - flutter/install_sdk:
  #          version: 3.3.10
  #      - run: flutter pub global activate melos 2.9.0
  #      - run: flutter pub global run melos bootstrap
  #      - run: flutter pub global run melos run exchange_rate_calculator_pub_get
    test:
      macos:
        xcode: 14.2.0
      steps:
        - run:
            command: echo "test daily memo"

    test2:
      macos:
        xcode: 14.2.0
      steps:
        - run:
            command: echo "test exchange cal"


workflows:
  ci:
    when: << pipeline.parameters.daily_memo_ci_run >>
    jobs:
      - test
  ci2:
    when: << pipeline.parameters.exchange_calculator_ci_run >>
    jobs:
      - test2
