version: '2.1'

orbs:
  flutter: circleci/flutter@2.0.2

parameters:
  daily_memo_ci_run:
    type: boolean
    default: false
  exchange_calculator_ci_run:
    type: boolean
    default: false

jobs:
  daily-memo-flutter-test:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run: flutter pub global activate melos 2.9.0
      - run: flutter pub global run melos bootstrap
      - run: flutter pub global run melos run daily_memo_test
      - run: flutter pub global run melos run daily_memo_build_apk
      - run: flutter pub global run melos run daily_memo_build_ipa

  daily-memo-build:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run: flutter pub global activate melos 2.9.0
      - run: flutter pub global run melos bootstrap
      - run: flutter pub global run melos daily_memo_pub_get
      - run: flutter pub global run melos run daily_memo_build_apk
      - run: flutter pub global run melos run daily_memo_build_ipa

  exchange-rate-cal-flutter-test:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run: flutter pub global activate melos 2.9.0
      - run: flutter pub global run melos bootstrap
      - run: flutter pub global run melos run exchange_rate_calculator_pub_get


workflows:
  daily-memo-app-ci-workflow:
    when: << pipeline.parameters.daily_memo_ci_run >>
    jobs:
      - daily-memo-flutter-test
      - daily-memo-build

  exchange-cal-app-ci-workflow:
    when: << pipeline.parameters.exchange_calculator_ci_run >>
    jobs:
      - test2
