#version: 2.1
#
#parameters:
#  is_daily_memo:
#    type: boolean
#    default: false
#  is_exchange_rate_calculator:
#    type: boolean
#    default: false
#  is_spiral_map:
#    type: boolean
#    default: false
#
#jobs:
#  common_pbr:
#
#workflows:
#  common_ci:
#    jobs:
#      - common_pbr

version: 2.1

parameters:

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  ci:
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run: flutter pub global activate melos 2.9.0
      - run: flutter pub global run melos bootstrap
      - run: flutter pub global run melos run daily_memo_pub_get

workflows:
  macos:
    xcode: 14.2.0
  main:
    jobs:
      - ci
